plugins {
    alias(libs.plugins.runpaper)
    alias(libs.plugins.pluginyml.paper)
}

dependencies {
    compileOnly(libs.paper)
}

tasks {
    clean {
        // Deletes the directory that is generated by the runPaper plugin
        delete("run")
    }
}

paper {
    name = "SignedVelocity"
    main = "io.github._4drian3d.signedvelocity.paper.SignedVelocity"
    authors = listOf("4drian3d")

    foliaSupported = true
    apiVersion = "1.19"
}
