plugins {
    alias(libs.plugins.runpaper)
}

dependencies {
    compileOnly(libs.paper)
}

tasks {
    clean {
        // Deletes the directory that is generated by the runPaper plugin
        delete("run")
    }
}
