name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
        cache: 'gradle'

    - name: Build with Gradle
      uses: nick-invision/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 2
        command: ./gradlew clean build
        